### ISSUE TITLE
Dark Mode Color Pallet

### ISSUE THREAD

**Issue by jeremylt** [Eudicods/outworlds-wastes#114]
It would be nice to respond to the user's dark mode vs light mode preferences.

See the deployed website here: https://outworlds-wastes.jeremylt.org/

The CSS file here should be updated to enable dark mode:
https://github.com/Eudicods/outworlds-wastes/blob/main/rules/style.css

Currently the site is fixed to light mode:
https://github.com/Eudicods/outworlds-wastes/blob/cf7fd8b1af921b345a17809c88787454f9bb4a85/rules/style.css#L137

Note: This website is built using LaTex. You do not need to futz with LaTeX. The built website source is on the `rules-web` branch:
https://github.com/Eudicods/outworlds-wastes/tree/rules-web

If you have questions, you can ask here, but for a more realtime back and forth, you can find me on the freeCodeCamp Discord:
https://www.freecodecamp.org/news/freecodecamp-discord-chat-room-server/

**Comment by RGHANILOO** [comment]
i was looking to implement the following 

```css
:root {
  color-scheme: light dark; /* Dark color-scheme added to the root */
}

@media (prefers-color-scheme: dark) {
  /* Dark theme styles go here */
}
 
@media (prefers-color-scheme: light) {
  /* Light theme styles go here */
}
```
with this update if a user has enabled dark mode from the system settings, they will get the dark mode styles by default

i would like to know :

- as the creator do you have preference of colour scheme for dark mode? 
- i would also like to test this theory locally, would appreciate any guidance you can provide in terms of being able to preview `.tex` file format in the browser (i have tried the following extensions in vscode without success, LaTeX previewer, LaTeX Workshop, )
